### ISSUE TITLE
server.auth.strategy 'session' has hard-coded password?

### ISSUE THREAD

**Issue by diracdeltas** [brave/vault#41]
in src/index.js:

```
  server.auth.strategy('session', 'cookie', {
    password: 'cookie-encryption-password',
    cookie: 'sid',
    isSecure: runtime.login.isSecure
  })
```

what is this auth strategy used for?

please address before open sourcing, thanks

**Comment by diracdeltas** [comment]
If we regenerate the string on startup, all user cookies are invalidated every time the server is restarted. Could we just put a randomly-generated string in config/config.development.js for this?

**Comment by therealklanni** [comment]
You're using MongdoDB, right? Why not store a randomly generated secure key there?

**Comment by bridiver** [comment]
What is this authentication for? I thought we weren't maintaining any session/cookie based logins for the vault anymore? We actually can't according to our current privacy policy.

**Comment by mrose17** [comment]
@therealklanni - hi! i like @diracdeltas' suggestion better because it fits in with the existing configuration file. there's nothing wrong with using a DB instead except that we currently don't  keep configuration in a database, it's in config/config.*.js (depending on whether the code is running on a server or under development or test)

**Comment by mrose17** [comment]
@bdriver - it is used by administrative users only, e.g., to populate the ad-manifest table...

**Comment by bridiver** [comment]
gotcha, thanks!

**Comment by mrose17** [comment]
@diracdeltas - what's your thinking on the PR?
